HTTP/1.1 200 OK
access-control-allow-headers: Authorization, Content-Type, Idempotency-Key, If-Match, Traceparent
access-control-allow-methods: GET, POST, PUT, OPTIONS
content-type: application/json; charset=utf-8
content-length: 36
Date: Tue, 01 Sep 2026 00:17:52 GMT
Connection: keep-alive
Keep-Alive: timeout=72

{"schema_version":1,"deliveries":[]}